# Generated by Django 2.2.10 on 2020-02-25 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excellent_Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('company', models.CharField(max_length=20, verbose_name='勤務先')),
                ('reason', models.CharField(choices=[('転職を検討していたから（給料の不満)', '転職を検討していたから（給料の不満）'), ('転職を検討していたから（昇進への不満)', '転職を検討していたから（昇進への不満）'), ('転職を検討していたから（会社方針の不満)', '転職を検討していたから（会社方針の不満）')], default='転職を検討していたから（給料の不満', max_length=100, verbose_name='推薦理由')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='emailアドレス')),
                ('more_information', models.TextField(verbose_name='詳細')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('who_recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
