# Generated by Django 2.2.9 on 2020-01-19 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excellent_Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('phone_number', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('more_information', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('who_recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
